### ISSUE TITLE
dataRetrieval: data discovery

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/training-curriculum#104]
Parent: dataRetrieval: accessing timeseries data

What data is available? 

- NWIS and WQP overview
- Basic web retrieval parameters
- Discovering data using dataRetrieval functions

**Comment by lindsaycarr** [comment]
I'm going to call this complete for now. Any additional changes based on WQP updates will be made along with the dataRetrieval updates. See https://github.com/USGS-R/dataRetrieval/issues/306 for more details.

**Comment by ldecicco-USGS** [comment]
Reopening because I'm not a fan of the line:
```
 It wouldn’t hurt to reinstall (see ?install.packages) so that you have the most up-to-date version.
```

I think we need to hammer home that people should update **all** of their packages. There's a small chance that people could take that line to mean:

```
install.packages("dataRetrieval", dependencies = FALSE)
```
And that has been a thorn in my side (only updating 1 package when all the other dependencies might be *really, really* old)

Also, I'm updating `dataRetrieval` to reflect this, but there's no:
UM (U.S. Minor Outlying Islands)
in the NWIS service, 

and currently "AS (American Samoa)" is not working (bug on NWIS...but we're going to add a fix on the dataRetrieval side, they are using an incorrect abbreviation "AQ").

**Comment by lindsaycarr** [comment]
Ah, good point about the package updating. How about that sentence reads: 
```Before continuing with this lesson, you should make sure that the dataRetrieval package is installed and loaded. If you haven't recently updated, you should reinstall the package by running install.packages('dataRetrieval`).```

There will be a section per #101 about installing packages. I think that would be a good place to put more detail about why updating is important. If you've got a spiel you give for that, can you copy/paste it into the issue?

I will delete "UM", but this won't be released until October so I imagine the AS issue would be fixed by then?

**Comment by lindsaycarr** [comment]
Sounds like this part is good now.
