### ISSUE TITLE
Defensive programming⁺

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/training-curriculum#154]
1. Define defensive programming.
2. List common techniques for defensive programming.
3. Construct and execute defensive programming functions.

`date: "9999-09-30"`

**Comment by lindsaycarr** [comment]
- `tryCatch()`, `stop()`, `match.args()`, `stopifnot()`
- imagine and catch all the weird things users might do
- see Hadley's stuff

**Comment by aappling-usgs** [comment]
Non-standard evaluation sometimes produces mysterious errors, says Hadley...but I can't think of any really good examples where NSE is worse than SE. Can anybody else? Here's the best I've come up with so far - it's obscure and unimpressive enough that I'm going to keep it out of my text, at least for now:

> * Scoping issues, where you expect a variable within one scope but R finds it in another instead. These are particularly insidious when combined with non-standard evaluation (NSE). Can you guess the outputs of these calls to `add_xy1` and `add_xy2`? If not, maybe your users shouldn't have to guess, either.
```{r, eval=FALSE}
x <- y <- 4
add_xy1 <- function(df, y) {
  dplyr::mutate(df, xy = x + y)$xy
}
add_xy1(df=data.frame(x=1), y=2)
add_xy1(df=data.frame(x=1, y=2), y=3)
add_xy1(df=data.frame(x=1))

add_xy2 <- function(df) {
  with(df, x + y)
}
add_xy2(df=data.frame(x=1, y=2))
add_xy2(df=data.frame(X=1, Y=2))
add_xy2(df=data.frame(x=1))
```

If anybody can come up with a more convincing example, I'm happy to add it. Especially if that example is more directly related to defensive programming than my above attempt - ideally, it would be a function that silently produces an unambiguously wrong result just because the user has an additional object present/absent in their global environment. Ideas, anybody?

**Comment by ldecicco-USGS** [comment]
Was thinking it could go in `tests`...but also here: possibly more info or examples on the `assertr` package, and maybe `validate`?

https://cran.r-project.org/web/packages/validate/vignettes/intro.html
