### ISSUE TITLE
some html tables extending outside of text region

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/training-curriculum#165]
![image](https://cloud.githubusercontent.com/assets/13220910/24465689/8b521bfa-1473-11e7-9cbb-8c5eef9b1741.png)

**Comment by mwernimont** [comment]
@lindsaycarr Can you give me a URL to this table, I haven't been able to find it on my own searching.

**Comment by lindsaycarr** [comment]
There's a couple on [this page](https://owi.usgs.gov/R/training-curriculum/usgs-packages/dataRetrieval-readNWIS/#readnwisgwl). To create them, I used an R package called `htmlTable` and created my own function to do it. [Here's where the function is called](https://github.com/USGS-R/training-curriculum/blob/master/content/usgs-packages/dataRetrieval_readNWIS.Rmd#readnwisgwl) and [here is where the function is defined](https://github.com/USGS-R/training-curriculum/blob/master/content/usgs-packages/arg_table_functions.R).

**Comment by mwernimont** [comment]
Cool, thank you, will investigate.

**Comment by mwernimont** [comment]
@lindsaycarr its an odd fix, but we have this wordbreak: keep all to avoid certain words splitting when descending onto the next line of the paragraph. The tables that are not wrapping and extruding from the divs are because we have sentences without proper spacing and the CSS is seeing them as whole words and not allowing them to break off to the next line.  We basically just need to go into the code and correctly space the sentences.  

The example I was working with was “America/Denver”,“America/Los_Angeles”, “America/Anchorage”,“America/Honolulu”, “America/Jamaica”,“America/Managua”, “America/Phoenix”, and “America/Metlakatla”

See how the quotes are touching the commas? Just gotta avoid that in the future.

Do you want me to go through and do the spacing?  I really don't know where all the problems places are, but seems to be when a tz category pops up.

**Comment by lindsaycarr** [comment]
Ah interesting! So the content in those tables are automatically generated based on the documentation that lives in the functions. I will go in and edit the function that makes them to add spaces between quotes. Thanks for hunting down the issue :heavy_check_mark:
